repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.9
    hooks:
      - id: trufflehog
        additional_dependencies: ["trufflehog"] 