services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9090:9090"  # Metrics port
    environment:
      - DATABASE_URL=postgresql://capsim_rw:${CAPSIM_RW_PASSWORD:-capsim_password}@postgres:5432/${POSTGRES_DB:-capsim}
      - DATABASE_URL_RO=postgresql://capsim_ro:${CAPSIM_RO_PASSWORD:-capsim_password}@postgres:5432/${POSTGRES_DB:-capsim}
      - POSTGRES_DB=${POSTGRES_DB:-capsim}
      - CAPSIM_RW_PASSWORD=${CAPSIM_RW_PASSWORD:-capsim_password}
      - CAPSIM_RO_PASSWORD=${CAPSIM_RO_PASSWORD:-capsim_password}
      - DOCKER_ENV=true
      - DECIDE_SCORE_THRESHOLD=${DECIDE_SCORE_THRESHOLD:-0.15}
      - TREND_ARCHIVE_THRESHOLD_DAYS=${TREND_ARCHIVE_THRESHOLD_DAYS:-3}
      - BASE_RATE=${BASE_RATE:-86.4}
      - BATCH_SIZE=${BATCH_SIZE:-20}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - ENABLE_JSON_LOGS=${ENABLE_JSON_LOGS:-true}
    labels:
      logging: "promtail"
      service.name: "capsim-app"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-capsim}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
      - CAPSIM_RW_PASSWORD=${CAPSIM_RW_PASSWORD:-capsim_password}
      - CAPSIM_RO_PASSWORD=${CAPSIM_RO_PASSWORD:-capsim_password}
    labels:
      logging: "promtail"
      service.name: "capsim-postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.40.0
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - default

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - promtail_data:/tmp
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - default

  grafana:
    image: grafana/grafana:9.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - loki

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  loki_data:
  promtail_data:
