apiVersion: 1

providers:
  - name: 'capsim-dashboards'
    orgId: 1
    folder: 'CAPSIM'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards 