server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)' 
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'
    pipeline_stages:
      # Parse database operations from postgres logs
      - match:
          selector: '{service_name="postgres"}'
          stages:
            - regex:
                expression: '.*statement:\s+(?P<sql_statement>.*)'
            - labels:
                log_type: "postgres_sql"
            - output:
                source: sql_statement
      
      # Parse INSERT operations into events table
      - match:
          selector: '{service_name="postgres"} |~ "INSERT INTO.*events"'
          stages:
            - labels:
                operation: "INSERT"
                table: "events"
                log_type: "events_insert"
      
      # Parse application logs
      - match:
          selector: '{service_name="app"}'
          stages:
            - labels:
                log_type: "application" 