{
 "title": "Events Table Real-time Monitoring",
 "tags": [
  "realtime",
  "events",
  "postgres"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cpu seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{job=\"prometheus\"}[1m])"
    }
   ]
  },
  {
   "title": "Parsed Events Parameters",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"capsim-postgres-1\"}"
    }
   ]
  },
  {
   "title": "Persons Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM capsim.persons"
    }
   ]
  },
  {
   "title": "Events Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM capsim.events"
    }
   ]
  },
  {
   "title": "Events INSERTs per Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"postgres\"} |~ \"INSERT INTO.*events\"[1m])"
    }
   ]
  },
  {
   "title": "Trends Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM capsim.trends"
    }
   ]
  },
  {
   "title": "Person attribute changes Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM capsim.person_attribute_history"
    }
   ]
  },
  {
   "title": "Real-time Events Table INSERTs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"postgres\"} |~ \"INSERT INTO.*events\""
    }
   ]
  },
  {
   "title": "Formatted Events Insert Details",
   "type": "logs",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{service_name=\"postgres\"} |~ \"INSERT INTO.*events\" | json | line_format \"{{.timestamp}} - Event Type: {{.event_type}} | Agent: {{.agent_id}} | Simulation: {{.simulation_id}} | Priority: {{.priority}}\""
    }
   ]
  }
 ]
}