# CAPSIM v1.9 Action Configuration
# Defines cooldowns, limits, effects, and profession weights for all agent actions

COOLDOWNS:
  POST_MIN: 40      # Согласно ТЗ v1.9
  SELF_DEV_MIN: 30  # Согласно ТЗ v1.9

LIMITS:
  MAX_PURCHASES_DAY: 5  # Согласно ТЗ v1.8

EFFECTS:
  POST:
    time_budget: -0.15   # Согласно ТЗ v1.9 (time_cost)
    energy_level: -0.20  # Согласно ТЗ v1.9 (energy_cost)
    social_status: 0.05  # Согласно ТЗ v1.9 (social_bonus)
  
  SELF_DEV:
    time_budget: -0.80   # Согласно ТЗ v1.9 (time_cost)
    energy_level: 0.45   # Согласно ТЗ v1.9 (energy_bonus)
    social_status: 0.10  # Согласно ТЗ v1.9 (social_bonus)
  
  PURCHASE:
    L1:
      cost_range: [0.1, 1.0]     # Согласно ТЗ v1.9
      energy_level: 0.30         # Согласно ТЗ v1.9 (energy_bonus)
      time_budget: -0.10         # Согласно ТЗ v1.9 (time_cost)
    L2:
      cost_range: [1.1, 2.4]     # Согласно ТЗ v1.9
      energy_level: 0.45         # Согласно ТЗ v1.9 (energy_bonus)
      time_budget: -0.10         # Согласно ТЗ v1.9 (time_cost)
      social_status: 0.05        # Согласно ТЗ v1.9 (social_bonus)
    L3:
      cost_range: [2.5, 3.5]     # Согласно ТЗ v1.9
      energy_level: 0.70         # Согласно ТЗ v1.9 (energy_bonus)
      time_budget: -0.10         # Согласно ТЗ v1.9 (time_cost)
      social_status: 0.20        # Согласно ТЗ v1.9 (social_bonus)

# Night recovery bonuses (v1.9 daily cycle)
NIGHT_RECOVERY:
  energy_bonus: 1.2
  financial_bonus: 1.0

SHOP_WEIGHTS:
  Businessman: 1.20
  Worker: 0.80
  Developer: 1.00
  Teacher: 0.90
  Doctor: 1.00
  Blogger: 1.05
  Politician: 1.15
  ShopClerk: 0.85
  Artist: 0.75
  SpiritualMentor: 0.80
  Philosopher: 0.75
  Unemployed: 0.60 