# CAPSIM v1.8 Action Configuration
# Defines cooldowns, limits, effects, and profession weights for all agent actions

COOLDOWNS:
  POST_MIN: 40      # v1.9: longer cooldown for posts
  SELF_DEV_MIN: 30  # v1.9 spec

LIMITS:
  MAX_PURCHASES_DAY: 8  # Increased to stimulate more purchase actions

EFFECTS:
  POST:
    time_budget: -0.15   # v1.9 time cost
    energy_level: -0.20  # v1.9 energy cost
    social_status: 0.05  # small immediate bonus
  
  SELF_DEV:
    time_budget: -0.80
    energy_level: 0.45
    social_status: 0.10
  
  PURCHASE:
    L1:
      cost_range: [0.1, 1.0]
      energy_level: 0.30
      time_budget: -0.10
    L2:
      cost_range: [1.1, 2.4]
      energy_level: 0.45
      time_budget: -0.10
      social_status: 0.05
    L3:
      cost_range: [2.5, 3.5]
      energy_level: 0.70
      time_budget: -0.10
      social_status: 0.20

# Night recovery bonuses (v1.9 daily cycle)
NIGHT_RECOVERY:
  energy_bonus: 1.2
  financial_bonus: 1.0

SHOP_WEIGHTS:
  Businessman: 1.20
  Worker: 0.80
  Developer: 1.00
  Teacher: 0.90
  Doctor: 1.00
  Blogger: 1.05
  Politician: 1.15
  ShopClerk: 0.85
  Artist: 0.75
  SpiritualMentor: 0.80
  Philosopher: 0.75
  Unemployed: 0.60 