# CAPSIM v1.8 Action Configuration
# Defines cooldowns, limits, effects, and profession weights for all agent actions

COOLDOWNS:
  POST_MIN: 30      # Reduced for higher activity
  SELF_DEV_MIN: 15  # Reduced for higher activity

LIMITS:
  MAX_PURCHASES_DAY: 5  # Maximum purchases per agent per day

EFFECTS:
  POST:
    time_budget: -0.20
    energy_level: -0.50
    social_status: 0.10
  
  SELF_DEV:
    time_budget: -1.00
    energy_level: 0.80
  
  PURCHASE:
    L1:
      financial_capability: -0.05
      energy_level: 0.20
    L2:
      financial_capability: -0.50
      energy_level: -0.10
      social_status: 0.20
    L3:
      financial_capability: -2.00
      energy_level: -0.15
      social_status: 1.00

SHOP_WEIGHTS:
  Businessman: 1.20
  Worker: 0.80
  Developer: 1.00
  Teacher: 0.90
  Doctor: 1.00
  Blogger: 1.05
  Politician: 1.15
  ShopClerk: 0.85
  Artist: 0.75
  SpiritualMentor: 0.80
  Philosopher: 0.75
  Unemployed: 0.60 