simulation_parameters:
  start_hour: 8
  end_hour: 23
  default_population: 1000

actions:
  - type: EducationAction
    params:
      level: "Bachelor"
      cost: 2.0
      income_boost: 1.0
      duration_days: 365
      energy_cost: 1.0
      time_cost: 4.0
  - type: WorkAction
    params:
      job_title: "Junior Developer"
      base_salary: 0.1 # This is a small boost to financial_capability per hour
      experience_required: 0
      energy_cost: 1.0
      time_cost: 1.0

professions:
  # Высокий социальный статус - более активные изменения trend_receptivity
  Businessman: { cluster: Social, count: 80, attributes: { financial_capability: [4, 5], trend_receptivity: [2.5, 4.5], social_status: [4, 5], energy_level: [3, 5], time_budget: [2, 4] } }
  Politician: { cluster: Social, count: 10, attributes: { financial_capability: [4, 5], trend_receptivity: [2.0, 4.5], social_status: [4, 5], energy_level: [3, 5], time_budget: [2, 4] } }
  Doctor: { cluster: Other, count: 50, attributes: { financial_capability: [3, 5], trend_receptivity: [1.5, 3.5], social_status: [3, 5], energy_level: [3, 5], time_budget: [2, 4] } }
  
  # Творческие профессии - высокая восприимчивость к трендам
  Blogger: { cluster: Social, count: 50, attributes: { financial_capability: [2, 4], trend_receptivity: [3.5, 5.0], social_status: [2, 4], energy_level: [3, 5], time_budget: [3, 5] } }
  Artist: { cluster: Worker, count: 70, attributes: { financial_capability: [1, 3], trend_receptivity: [3.0, 5.0], social_status: [1, 3], energy_level: [3, 5], time_budget: [3, 5] } }
  
  # Технические профессии - умеренная восприимчивость
  Developer: { cluster: Worker, count: 120, attributes: { financial_capability: [3, 5], trend_receptivity: [2.0, 4.0], social_status: [2, 4], energy_level: [3, 5], time_budget: [2, 4] } }
  Teacher: { cluster: Other, count: 100, attributes: { financial_capability: [2, 4], trend_receptivity: [1.5, 3.5], social_status: [2, 4], energy_level: [3, 5], time_budget: [2, 4] } }
  
  # Рабочие профессии - средняя восприимчивость
  Worker: { cluster: Worker, count: 100, attributes: { financial_capability: [2, 4], trend_receptivity: [2.0, 4.0], social_status: [1, 3], energy_level: [3, 5], time_budget: [2, 4] } }
  ShopClerk: { cluster: Worker, count: 180, attributes: { financial_capability: [1, 3], trend_receptivity: [2.0, 4.0], social_status: [1, 3], energy_level: [3, 5], time_budget: [2, 4] } }
  
  # Духовные профессии - стабильная, но изменчивая восприимчивость
  SpiritualMentor: { cluster: Spiritual, count: 30, attributes: { financial_capability: [1, 3], trend_receptivity: [2.0, 4.0], social_status: [2, 4], energy_level: [4, 5], time_budget: [3, 5] } }
  Philosopher: { cluster: Spiritual, count: 20, attributes: { financial_capability: [1, 3], trend_receptivity: [1.5, 4.0], social_status: [2, 4], energy_level: [3, 5], time_budget: [3, 5] } }
  
  # Безработные - высокая восприимчивость из-за свободного времени
  Unemployed: { cluster: Other, count: 90, attributes: { financial_capability: [1, 2], trend_receptivity: [2.5, 4.5], social_status: [1, 2], energy_level: [2, 4], time_budget: [4, 5] } }