apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ['grafana_folder', 'alertname']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: performance-alerts-email
        matchers:
          - alertname =~ "CpuTemperatureHigh|HighIOWait|WalSpikes|P95WriteLatencyHigh"
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 5m
        continue: true
      
      - receiver: performance-alerts-browser
        matchers:
          - alertname =~ "CpuTemperatureHigh|HighIOWait|WalSpikes|P95WriteLatencyHigh"
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 10m 